# Generated by Django 5.0 on 2024-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CATApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="choice", name="career"),
        migrations.AddField(
            model_name="choice", name="career", field=models.JSONField()
        ),
    ]
