# Generated by Django 5.0 on 2024-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CATApp', '0003_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('response', models.JSONField()),
                ('results', models.JSONField()),
            ],
        ),
    ]
